export const mockJuradosData = {

    juradoSorteadoBasico: {
        nome: 'Jurado Sorteado',
        profissao: 'Testador profissional',
        cpf: '111.111.111-11',
        status: null
    },

    juradoSorteadoCompleto: {
        "id": 27,
        "nome": "João Lima",
        "nomeSocial": "",
        "genero": "Feminino",
        "rg": "51906422-7",
        "cpf": 62395951382,
        "email": "joao.lima7194@outlook.com",
        "endereco": "Rua do Sol, 526, Curitiba",
        "escolaridade": "Médio Incompleto",
        "profissao": "Desenvolvedor",
        "nascimento": "03/07/1995",
        "tipoJurado": "Titular"
    },

    juradosTitularesMock: [
        {
            "id": 27,
            "nome": "João Lima",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "51906422-7",
            "cpf": 62395951382,
            "email": "joao.lima7194@outlook.com",
            "endereco": "Rua do Sol, 526, Curitiba",
            "escolaridade": "Médio Incompleto",
            "profissao": "Desenvolvedor",
            "nascimento": "03/07/1995",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 56,
            "nome": "Fernanda Silva",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "33357359-6",
            "cpf": 85549948666,
            "email": "fernanda.silva3000@yahoo.com",
            "endereco": "Rua da Paz, 673, São Paulo",
            "escolaridade": "Superior Incompleto",
            "profissao": "Chef",
            "nascimento": "05/05/1990",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 79,
            "nome": "Sofia Santos",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "70199938-8",
            "cpf": 59770358764,
            "email": "sofia.santos2366@gmail.com",
            "endereco": "Rua da Paz, 869, Brasília",
            "escolaridade": "Fundamental Completo",
            "profissao": "Jornalista",
            "nascimento": "23/03/1980",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 92,
            "nome": "Fernanda Santos",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "80393616-3",
            "cpf": 48450000185,
            "email": "fernanda.santos2917@hotmail.com",
            "endereco": "Rua da Paz, 322, Rio de Janeiro",
            "escolaridade": "Fundamental Incompleto",
            "profissao": "Psicólogo",
            "nascimento": "02/12/1969",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 176,
            "nome": "Luísa Souza",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "74115978-4",
            "cpf": 48701236280,
            "email": "luisa.souza941@uol.com.br",
            "endereco": "Rua da Paz, 912, Curitiba",
            "escolaridade": "Fundamental Incompleto",
            "profissao": "Veterinário",
            "nascimento": "12/06/1990",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 177,
            "nome": "Sofia Santos",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "45695795-1",
            "cpf": 13225229396,
            "email": "sofia.santos3236@yahoo.com",
            "endereco": "Rua das Palmeiras, 101, Rio de Janeiro",
            "escolaridade": "Médio Completo",
            "profissao": "Policial",
            "nascimento": "26/10/1989",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 261,
            "nome": "Rafael Oliveira",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "61284169-4",
            "cpf": 8070036530,
            "email": "rafael.oliveira1035@outlook.com",
            "endereco": "Travessa Central, 563, Salvador",
            "escolaridade": "Médio Incompleto",
            "profissao": "Músico",
            "nascimento": "30/05/1960",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 319,
            "nome": "Luísa Pereira",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "67953949-7",
            "cpf": 73024619649,
            "email": "luisa.pereira2971@uol.com.br",
            "endereco": "Travessa Central, 751, Porto Alegre",
            "escolaridade": "Superior Incompleto",
            "profissao": "Outros",
            "nascimento": "05/02/1976",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 345,
            "nome": "Rafael Silva",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "42833954-4",
            "cpf": 41281176345,
            "email": "rafael.silva6465@outlook.com",
            "endereco": "Avenida Brasil, 117, São Paulo",
            "escolaridade": "Fundamental Completo",
            "profissao": "Contador",
            "nascimento": "01/11/2003",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 357,
            "nome": "Ana Souza",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "41120958-3",
            "cpf": 77119225020,
            "email": "ana.souza4542@outlook.com",
            "endereco": "Rua do Sol, 768, São Paulo",
            "escolaridade": "Superior Incompleto",
            "profissao": "Jornalista",
            "nascimento": "19/06/1995",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 411,
            "nome": "João Santos",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "65519865-1",
            "cpf": 64568177818,
            "email": "joao.santos5773@uol.com.br",
            "endereco": "Rua das Palmeiras, 693, Brasília",
            "escolaridade": "Superior Completo",
            "profissao": "Veterinário",
            "nascimento": "11/07/1952",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 449,
            "nome": "Sofia Rodrigues",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "56052565-2",
            "cpf": 54970479343,
            "email": "sofia.rodrigues9344@outlook.com",
            "endereco": "Rua das Flores, 495, Salvador",
            "escolaridade": "Médio Completo",
            "profissao": "Designer",
            "nascimento": "27/08/1991",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 527,
            "nome": "Pedro Costa",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "14082126-7",
            "cpf": 80518615785,
            "email": "pedro.costa718@uol.com.br",
            "endereco": "Rua da Paz, 162, Curitiba",
            "escolaridade": "Pós-graduação",
            "profissao": "Policial",
            "nascimento": "08/03/2004",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 552,
            "nome": "Gabriel Oliveira",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "62217068-8",
            "cpf": 72359323716,
            "email": "gabriel.oliveira2308@yahoo.com",
            "endereco": "Avenida Brasil, 261, Rio de Janeiro",
            "escolaridade": "Superior Completo",
            "profissao": "Cientista",
            "nascimento": "21/04/1988",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 563,
            "nome": "Gabriel Pereira",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "97158926-0",
            "cpf": 33393444990,
            "email": "gabriel.pereira5230@gmail.com",
            "endereco": "Rua das Flores, 821, Porto Alegre",
            "escolaridade": "Médio Completo",
            "profissao": "Médico",
            "nascimento": "20/09/1950",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 575,
            "nome": "Pedro Lima",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "88597511-2",
            "cpf": 4439223790,
            "email": "pedro.lima3564@gmail.com",
            "endereco": "Rua do Sol, 119, Belo Horizonte",
            "escolaridade": "Fundamental Incompleto",
            "profissao": "Outros",
            "nascimento": "19/01/1976",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 582,
            "nome": "Rafael Pereira",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "31590986-2",
            "cpf": 12431941350,
            "email": "rafael.pereira6546@hotmail.com",
            "endereco": "Rua das Flores, 88, Belo Horizonte",
            "escolaridade": "Superior Completo",
            "profissao": "Engenheiro",
            "nascimento": "14/01/1978",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 589,
            "nome": "Ana Oliveira",
            "nomeSocial": "",
            "genero": "Outro",
            "rg": "76198784-1",
            "cpf": 4738325233,
            "email": "ana.oliveira8538@yahoo.com",
            "endereco": "Rua da Paz, 955, Salvador",
            "escolaridade": "Médio Completo",
            "profissao": "Psicólogo",
            "nascimento": "07/08/1988",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 598,
            "nome": "Sofia Santos",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "74295059-6",
            "cpf": 50941178091,
            "email": "sofia.santos616@gmail.com",
            "endereco": "Rua das Palmeiras, 337, Curitiba",
            "escolaridade": "Superior Completo",
            "profissao": "Desenvolvedor",
            "nascimento": "26/12/1954",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 627,
            "nome": "Maria Costa",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "32240193-0",
            "cpf": 15933644932,
            "email": "maria.costa1695@uol.com.br",
            "endereco": "Rua das Flores, 519, São Paulo",
            "escolaridade": "Fundamental Completo",
            "profissao": "Professor",
            "nascimento": "18/11/2003",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 650,
            "nome": "Luísa Martins",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "64538580-0",
            "cpf": 33037116217,
            "email": "luisa.martins4424@gmail.com",
            "endereco": "Avenida Brasil, 581, São Paulo",
            "escolaridade": "Superior Incompleto",
            "profissao": "Outros",
            "nascimento": "04/10/1962",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 663,
            "nome": "Rafael Lima",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "80877500-0",
            "cpf": 18752649168,
            "email": "rafael.lima5952@gmail.com",
            "endereco": "Rua das Palmeiras, 818, Salvador",
            "escolaridade": "Superior Completo",
            "profissao": "Jornalista",
            "nascimento": "15/02/1952",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 667,
            "nome": "Maria Almeida",
            "nomeSocial": "",
            "genero": "Masculino",
            "rg": "96043473-8",
            "cpf": 48708378582,
            "email": "maria.almeida615@yahoo.com",
            "endereco": "Rua das Palmeiras, 315, Brasília",
            "escolaridade": "Médio Completo",
            "profissao": "Contador",
            "nascimento": "11/01/1970",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 758,
            "nome": "Gabriel Oliveira",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "78333563-9",
            "cpf": 79541492499,
            "email": "gabriel.oliveira3003@outlook.com",
            "endereco": "Rua das Flores, 245, Curitiba",
            "escolaridade": "Fundamental Incompleto",
            "profissao": "Advogado",
            "nascimento": "28/01/1959",
            "tipoJurado": "Titular",
            "status": null
        },
        {
            "id": 771,
            "nome": "Carlos Martins",
            "nomeSocial": "",
            "genero": "Feminino",
            "rg": "68513856-5",
            "cpf": 4542085858,
            "email": "carlos.martins524@hotmail.com",
            "endereco": "Travessa Central, 23, Brasília",
            "escolaridade": "Médio Completo",
            "profissao": "Psicólogo",
            "nascimento": "02/03/1962",
            "tipoJurado": "Titular",
            "status": null
        }
    ]
}