import { JuradoSorteado } from "../../model/JuradoSorteado.js"
import { Jurado } from "../../model/Jurado.js";

const juradosSorteadosRawData = [
    {
        "id": 90,
        "nome": "Gabriel Costa",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 74924434172,
        "email": "gabriel.costa3175@gmail.com",
        "endereco": "Rua das Palmeiras, 969, Salvador",
        "escolaridade": "Superior Completo",
        "profissao": "Policial",
        "nascimento": "13/01/1958",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 133,
        "nome": "Carlos Silva",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 48417904897,
        "email": "carlos.silva6102@uol.com.br",
        "endereco": "Rua do Sol, 548, Belo Horizonte",
        "escolaridade": "Fundamental Incompleto",
        "profissao": "Veterinário",
        "nascimento": "16/01/1957",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 158,
        "nome": "Ana Santos",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 7534894457,
        "email": "ana.santos6327@yahoo.com",
        "endereco": "Avenida Brasil, 793, Brasília",
        "escolaridade": "Superior Completo",
        "profissao": "Enfermeiro",
        "nascimento": "10/05/1953",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 189,
        "nome": "Carlos Silva",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 30895552588,
        "email": "carlos.silva7771@gmail.com",
        "endereco": "Avenida Brasil, 29, Brasília",
        "escolaridade": "Médio Incompleto",
        "profissao": "Contador",
        "nascimento": "16/08/1963",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 210,
        "nome": "João Almeida",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 6539207727,
        "email": "joao.almeida1250@uol.com.br",
        "endereco": "Rua das Palmeiras, 230, São Paulo",
        "escolaridade": "Superior Completo",
        "profissao": "Enfermeiro",
        "nascimento": "21/06/1988",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 240,
        "nome": "Ana Santos",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 52841011360,
        "email": "ana.santos1313@outlook.com",
        "endereco": "Travessa Central, 647, Curitiba",
        "escolaridade": "Pós-graduação",
        "profissao": "Músico",
        "nascimento": "05/10/1976",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 284,
        "nome": "Maria Santos",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 16521108501,
        "email": "maria.santos8960@hotmail.com",
        "endereco": "Rua do Sol, 154, Belo Horizonte",
        "escolaridade": "Médio Completo",
        "profissao": "Designer",
        "nascimento": "03/09/1989",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 292,
        "nome": "Maria Silva",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 56659700409,
        "email": "maria.silva8404@outlook.com",
        "endereco": "Avenida Brasil, 972, Porto Alegre",
        "escolaridade": "Superior Completo",
        "profissao": "Chef",
        "nascimento": "14/06/1956",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 333,
        "nome": "Carlos Martins",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 84656070713,
        "email": "carlos.martins1864@gmail.com",
        "endereco": "Rua do Sol, 292, Belo Horizonte",
        "escolaridade": "Pós-graduação",
        "profissao": "Piloto",
        "nascimento": "23/04/1988",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 381,
        "nome": "Pedro Lima",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 73717237727,
        "email": "pedro.lima845@hotmail.com",
        "endereco": "Rua das Palmeiras, 35, Rio de Janeiro",
        "escolaridade": "Médio Incompleto",
        "profissao": "Desenvolvedor",
        "nascimento": "01/05/1971",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 389,
        "nome": "Sofia Almeida",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 32347540672,
        "email": "sofia.almeida255@hotmail.com",
        "endereco": "Travessa Central, 60, Rio de Janeiro",
        "escolaridade": "Fundamental Completo",
        "profissao": "Designer",
        "nascimento": "22/01/1998",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 420,
        "nome": "Gabriel Silva",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 585509674,
        "email": "gabriel.silva5489@hotmail.com",
        "endereco": "Travessa Central, 573, Porto Alegre",
        "escolaridade": "Superior Completo",
        "profissao": "Designer",
        "nascimento": "24/05/1995",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 423,
        "nome": "Luísa Oliveira",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 62565296508,
        "email": "luisa.oliveira3728@hotmail.com",
        "endereco": "Rua da Paz, 144, Rio de Janeiro",
        "escolaridade": "Fundamental Completo",
        "profissao": "Desenvolvedor",
        "nascimento": "12/06/2002",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 479,
        "nome": "Gabriel Costa",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 28756099456,
        "email": "gabriel.costa402@yahoo.com",
        "endereco": "Travessa Central, 55, Rio de Janeiro",
        "escolaridade": "Superior Incompleto",
        "profissao": "Músico",
        "nascimento": "18/10/1954",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 501,
        "nome": "Gabriel Souza",
        "nomeSocial": "Fernanda Souza",
        "genero": "Outro",
        "cpf": 67463289151,
        "email": "gabriel.souza6809@uol.com.br",
        "endereco": "Rua das Flores, 656, São Paulo",
        "escolaridade": "Superior Completo",
        "profissao": "Advogado",
        "nascimento": "03/01/1994",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 541,
        "nome": "Pedro Costa",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 97382710961,
        "email": "pedro.costa264@yahoo.com",
        "endereco": "Rua do Sol, 169, São Paulo",
        "escolaridade": "Fundamental Completo",
        "profissao": "Jornalista",
        "nascimento": "04/12/1977",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 579,
        "nome": "Sofia Oliveira",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 73997203085,
        "email": "sofia.oliveira8442@yahoo.com",
        "endereco": "Rua do Sol, 687, Curitiba",
        "escolaridade": "Pós-graduação",
        "profissao": "Agricultor",
        "nascimento": "02/12/1999",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 607,
        "nome": "João Pereira",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 24133058457,
        "email": "joao.pereira7904@hotmail.com",
        "endereco": "Rua da Paz, 840, Belo Horizonte",
        "escolaridade": "Fundamental Completo",
        "profissao": "Desenvolvedor",
        "nascimento": "05/03/1976",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 614,
        "nome": "Luísa Oliveira",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 1053197941,
        "email": "luisa.oliveira5467@outlook.com",
        "endereco": "Rua do Sol, 579, São Paulo",
        "escolaridade": "Superior Completo",
        "profissao": "Professor",
        "nascimento": "01/05/1975",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 660,
        "nome": "Pedro Martins",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 64314984081,
        "email": "pedro.martins4933@yahoo.com",
        "endereco": "Rua do Sol, 741, Porto Alegre",
        "escolaridade": "Superior Completo",
        "profissao": "Jornalista",
        "nascimento": "28/03/1959",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 668,
        "nome": "Rafael Silva",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 58047755742,
        "email": "rafael.silva8955@hotmail.com",
        "endereco": "Avenida Brasil, 967, Curitiba",
        "escolaridade": "Superior Completo",
        "profissao": "Professor",
        "nascimento": "03/07/2004",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 675,
        "nome": "João Silva",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 32741831764,
        "email": "joao.silva61@gmail.com",
        "endereco": "Rua da Paz, 990, Belo Horizonte",
        "escolaridade": "Médio Incompleto",
        "profissao": "Desenvolvedor",
        "nascimento": "24/10/1960",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 677,
        "nome": "Rafael Souza",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 83646237567,
        "email": "rafael.souza5658@hotmail.com",
        "endereco": "Travessa Central, 578, Porto Alegre",
        "escolaridade": "Fundamental Incompleto",
        "profissao": "Desenvolvedor",
        "nascimento": "04/04/1979",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 680,
        "nome": "Maria Santos",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 70194756258,
        "email": "maria.santos2789@hotmail.com",
        "endereco": "Travessa Central, 752, Salvador",
        "escolaridade": "Fundamental Completo",
        "profissao": "Piloto",
        "nascimento": "03/06/1953",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 729,
        "nome": "Fernanda Lima",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 687709896,
        "email": "fernanda.lima9895@hotmail.com",
        "endereco": "Travessa Central, 946, Rio de Janeiro",
        "escolaridade": "Superior Incompleto",
        "profissao": "Advogado",
        "nascimento": "09/06/1978",
        "tipoJurado": "Titular",
        "status": null
    },
    {
        "id": 55,
        "nome": "Maria Souza",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 97969280800,
        "email": "maria.souza1927@gmail.com",
        "endereco": "Rua das Flores, 910, Curitiba",
        "escolaridade": "Superior Completo",
        "profissao": "Outros",
        "nascimento": "15/02/1985",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 67,
        "nome": "Ana Pereira",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 14471618318,
        "email": "ana.pereira40@gmail.com",
        "endereco": "Rua da Paz, 605, São Paulo",
        "escolaridade": "Superior Completo",
        "profissao": "Contador",
        "nascimento": "17/09/1968",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 178,
        "nome": "João Lima",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 2666998891,
        "email": "joao.lima4273@gmail.com",
        "endereco": "Avenida Brasil, 431, Salvador",
        "escolaridade": "Fundamental Incompleto",
        "profissao": "Designer",
        "nascimento": "27/04/2000",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 232,
        "nome": "Maria Almeida",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 47369701638,
        "email": "maria.almeida878@outlook.com",
        "endereco": "Rua da Paz, 825, Belo Horizonte",
        "escolaridade": "Pós-graduação",
        "profissao": "Psicólogo",
        "nascimento": "12/10/1961",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 257,
        "nome": "João Lima",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 8877697629,
        "email": "joao.lima9912@gmail.com",
        "endereco": "Travessa Central, 878, Rio de Janeiro",
        "escolaridade": "Superior Incompleto",
        "profissao": "Engenheiro",
        "nascimento": "08/12/1953",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 299,
        "nome": "Sofia Souza",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 95853331229,
        "email": "sofia.souza258@hotmail.com",
        "endereco": "Travessa Central, 40, Curitiba",
        "escolaridade": "Médio Completo",
        "profissao": "Jornalista",
        "nascimento": "10/05/1990",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 361,
        "nome": "Carlos Santos",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 47497546416,
        "email": "carlos.santos1203@yahoo.com",
        "endereco": "Rua das Palmeiras, 280, Rio de Janeiro",
        "escolaridade": "Pós-graduação",
        "profissao": "Outros",
        "nascimento": "09/12/1978",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 368,
        "nome": "João Lima",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 31815005461,
        "email": "joao.lima3653@hotmail.com",
        "endereco": "Rua do Sol, 318, São Paulo",
        "escolaridade": "Fundamental Incompleto",
        "profissao": "Advogado",
        "nascimento": "01/04/1980",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 377,
        "nome": "Rafael Rodrigues",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 340591607,
        "email": "rafael.rodrigues4144@uol.com.br",
        "endereco": "Avenida Brasil, 799, Curitiba",
        "escolaridade": "Fundamental Completo",
        "profissao": "Professor",
        "nascimento": "26/12/1971",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 387,
        "nome": "Gabriel Santos",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 57662782986,
        "email": "gabriel.santos832@gmail.com",
        "endereco": "Rua das Flores, 387, Porto Alegre",
        "escolaridade": "Médio Incompleto",
        "profissao": "Engenheiro",
        "nascimento": "18/04/1975",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 394,
        "nome": "Ana Lima",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 78254406475,
        "email": "ana.lima5645@yahoo.com",
        "endereco": "Rua da Paz, 517, Brasília",
        "escolaridade": "Fundamental Completo",
        "profissao": "Arquiteto",
        "nascimento": "02/09/1991",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 432,
        "nome": "Rafael Santos",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 10194863092,
        "email": "rafael.santos6835@yahoo.com",
        "endereco": "Avenida Brasil, 48, Brasília",
        "escolaridade": "Superior Completo",
        "profissao": "Outros",
        "nascimento": "10/02/1981",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 437,
        "nome": "Gabriel Lima",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 68230728239,
        "email": "gabriel.lima9504@yahoo.com",
        "endereco": "Rua das Flores, 588, Brasília",
        "escolaridade": "Pós-graduação",
        "profissao": "Arquiteto",
        "nascimento": "09/09/1983",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 439,
        "nome": "Ana Santos",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 1136671852,
        "email": "ana.santos4605@hotmail.com",
        "endereco": "Rua da Paz, 424, Salvador",
        "escolaridade": "Superior Incompleto",
        "profissao": "Policial",
        "nascimento": "15/03/1970",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 491,
        "nome": "Ana Rodrigues",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 89688655080,
        "email": "ana.rodrigues2820@yahoo.com",
        "endereco": "Rua das Palmeiras, 310, São Paulo",
        "escolaridade": "Pós-graduação",
        "profissao": "Médico",
        "nascimento": "25/09/1994",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 529,
        "nome": "Luísa Santos",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 61592949110,
        "email": "luisa.santos7611@gmail.com",
        "endereco": "Travessa Central, 259, Porto Alegre",
        "escolaridade": "Médio Incompleto",
        "profissao": "Jornalista",
        "nascimento": "03/06/1973",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 567,
        "nome": "Sofia Silva",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 16910926262,
        "email": "sofia.silva4460@hotmail.com",
        "endereco": "Rua das Flores, 290, São Paulo",
        "escolaridade": "Superior Incompleto",
        "profissao": "Fotógrafo",
        "nascimento": "28/08/2005",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 589,
        "nome": "Ana Oliveira",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 4738325233,
        "email": "ana.oliveira8538@yahoo.com",
        "endereco": "Rua da Paz, 955, Salvador",
        "escolaridade": "Médio Completo",
        "profissao": "Psicólogo",
        "nascimento": "07/08/1988",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 664,
        "nome": "Gabriel Almeida",
        "nomeSocial": "",
        "genero": "Outro",
        "cpf": 95038077792,
        "email": "gabriel.almeida7301@yahoo.com",
        "endereco": "Rua das Flores, 73, Porto Alegre",
        "escolaridade": "Superior Completo",
        "profissao": "Médico",
        "nascimento": "19/11/1956",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 699,
        "nome": "Fernanda Santos",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 59755565624,
        "email": "fernanda.santos9156@uol.com.br",
        "endereco": "Rua das Flores, 593, Salvador",
        "escolaridade": "Fundamental Completo",
        "profissao": "Designer",
        "nascimento": "03/06/2000",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 708,
        "nome": "Pedro Souza",
        "nomeSocial": "",
        "genero": "Masculino",
        "cpf": 1859041621,
        "email": "pedro.souza5997@uol.com.br",
        "endereco": "Rua das Flores, 926, Belo Horizonte",
        "escolaridade": "Fundamental Completo",
        "profissao": "Piloto",
        "nascimento": "05/06/1999",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 713,
        "nome": "Fernanda Almeida",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 31909218023,
        "email": "fernanda.almeida3552@gmail.com",
        "endereco": "Rua do Sol, 685, Curitiba",
        "escolaridade": "Superior Incompleto",
        "profissao": "Fotógrafo",
        "nascimento": "21/09/1981",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 739,
        "nome": "Gabriel Souza",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 41793394245,
        "email": "gabriel.souza3530@hotmail.com",
        "endereco": "Avenida Brasil, 750, Belo Horizonte",
        "escolaridade": "Fundamental Completo",
        "profissao": "Engenheiro",
        "nascimento": "13/01/1984",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 742,
        "nome": "João Almeida",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 65129444911,
        "email": "joao.almeida2381@hotmail.com",
        "endereco": "Avenida Brasil, 505, Brasília",
        "escolaridade": "Pós-graduação",
        "profissao": "Designer",
        "nascimento": "07/11/1981",
        "tipoJurado": "Suplente",
        "status": null
    },
    {
        "id": 751,
        "nome": "Luísa Costa",
        "nomeSocial": "",
        "genero": "Feminino",
        "cpf": 24894281886,
        "email": "luisa.costa8971@yahoo.com",
        "endereco": "Rua do Sol, 633, Brasília",
        "escolaridade": "Superior Incompleto",
        "profissao": "Médico",
        "nascimento": "12/11/1997",
        "tipoJurado": "Suplente",
        "status": null
    }
]


//Todos os jurados (titulares e suplentes)
export const juradosMockAll = juradosSorteadosRawData.
    map(
        data => {
            const juradoBase = new Jurado(
                data.id,
                data.nome,
                data.nomeSocial,
                '',
                data.cpf,
                data.email,
                data.endereco,
                data.profissao,
                data.nascimento,
                data.genero,
                data.escolaridade
            );
            return new JuradoSorteado(juradoBase, data.tipoJurado);
        }
    );

//Apenas titulares
export const juradosTitularesMock = juradosMockAll.
    filter(
        (juradoSorteado) => {
            juradoSorteado.tipoJurado === 'Titular';
        }
    );

export const juradosSuplentesMock = juradosMockAll.
    filter(
        (juradoSorteado) => {
            juradoSorteado.tipoJurado === 'Suplente';
        }
    );