import { JuradoSorteado } from "../../model/JuradoSorteado.js"
import { Jurado } from "../../model/Jurado.js"

const juradosTitularesMockRawData = [
  {
    "id": 90,
    "nome": "Gabriel Costa",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 74924434172,
    "email": "gabriel.costa3175@gmail.com",
    "endereco": "Rua das Palmeiras, 969, Salvador",
    "escolaridade": "Superior Completo",
    "profissao": "Policial",
    "nascimento": "13/01/1958",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 133,
    "nome": "Carlos Silva",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 48417904897,
    "email": "carlos.silva6102@uol.com.br",
    "endereco": "Rua do Sol, 548, Belo Horizonte",
    "escolaridade": "Fundamental Incompleto",
    "profissao": "Veterinário",
    "nascimento": "16/01/1957",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 158,
    "nome": "Ana Santos",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 7534894457,
    "email": "ana.santos6327@yahoo.com",
    "endereco": "Avenida Brasil, 793, Brasília",
    "escolaridade": "Superior Completo",
    "profissao": "Enfermeiro",
    "nascimento": "10/05/1953",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 189,
    "nome": "Carlos Silva",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 30895552588,
    "email": "carlos.silva7771@gmail.com",
    "endereco": "Avenida Brasil, 29, Brasília",
    "escolaridade": "Médio Incompleto",
    "profissao": "Contador",
    "nascimento": "16/08/1963",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 210,
    "nome": "João Almeida",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 6539207727,
    "email": "joao.almeida1250@uol.com.br",
    "endereco": "Rua das Palmeiras, 230, São Paulo",
    "escolaridade": "Superior Completo",
    "profissao": "Enfermeiro",
    "nascimento": "21/06/1988",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 240,
    "nome": "Ana Santos",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 52841011360,
    "email": "ana.santos1313@outlook.com",
    "endereco": "Travessa Central, 647, Curitiba",
    "escolaridade": "Pós-graduação",
    "profissao": "Músico",
    "nascimento": "05/10/1976",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 284,
    "nome": "Maria Santos",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 16521108501,
    "email": "maria.santos8960@hotmail.com",
    "endereco": "Rua do Sol, 154, Belo Horizonte",
    "escolaridade": "Médio Completo",
    "profissao": "Designer",
    "nascimento": "03/09/1989",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 292,
    "nome": "Maria Silva",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 56659700409,
    "email": "maria.silva8404@outlook.com",
    "endereco": "Avenida Brasil, 972, Porto Alegre",
    "escolaridade": "Superior Completo",
    "profissao": "Chef",
    "nascimento": "14/06/1956",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 333,
    "nome": "Carlos Martins",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 84656070713,
    "email": "carlos.martins1864@gmail.com",
    "endereco": "Rua do Sol, 292, Belo Horizonte",
    "escolaridade": "Pós-graduação",
    "profissao": "Piloto",
    "nascimento": "23/04/1988",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 381,
    "nome": "Pedro Lima",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 73717237727,
    "email": "pedro.lima845@hotmail.com",
    "endereco": "Rua das Palmeiras, 35, Rio de Janeiro",
    "escolaridade": "Médio Incompleto",
    "profissao": "Desenvolvedor",
    "nascimento": "01/05/1971",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 389,
    "nome": "Sofia Almeida",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 32347540672,
    "email": "sofia.almeida255@hotmail.com",
    "endereco": "Travessa Central, 60, Rio de Janeiro",
    "escolaridade": "Fundamental Completo",
    "profissao": "Designer",
    "nascimento": "22/01/1998",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 420,
    "nome": "Gabriel Silva",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 585509674,
    "email": "gabriel.silva5489@hotmail.com",
    "endereco": "Travessa Central, 573, Porto Alegre",
    "escolaridade": "Superior Completo",
    "profissao": "Designer",
    "nascimento": "24/05/1995",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 423,
    "nome": "Luísa Oliveira",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 62565296508,
    "email": "luisa.oliveira3728@hotmail.com",
    "endereco": "Rua da Paz, 144, Rio de Janeiro",
    "escolaridade": "Fundamental Completo",
    "profissao": "Desenvolvedor",
    "nascimento": "12/06/2002",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 479,
    "nome": "Gabriel Costa",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 28756099456,
    "email": "gabriel.costa402@yahoo.com",
    "endereco": "Travessa Central, 55, Rio de Janeiro",
    "escolaridade": "Superior Incompleto",
    "profissao": "Músico",
    "nascimento": "18/10/1954",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 501,
    "nome": "Gabriel Souza",
    "nomeSocial": "Fernanda Souza",
    "genero": "Outro",
    "cpf": 67463289151,
    "email": "gabriel.souza6809@uol.com.br",
    "endereco": "Rua das Flores, 656, São Paulo",
    "escolaridade": "Superior Completo",
    "profissao": "Advogado",
    "nascimento": "03/01/1994",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 541,
    "nome": "Pedro Costa",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 97382710961,
    "email": "pedro.costa264@yahoo.com",
    "endereco": "Rua do Sol, 169, São Paulo",
    "escolaridade": "Fundamental Completo",
    "profissao": "Jornalista",
    "nascimento": "04/12/1977",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 579,
    "nome": "Sofia Oliveira",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 73997203085,
    "email": "sofia.oliveira8442@yahoo.com",
    "endereco": "Rua do Sol, 687, Curitiba",
    "escolaridade": "Pós-graduação",
    "profissao": "Agricultor",
    "nascimento": "02/12/1999",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 607,
    "nome": "João Pereira",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 24133058457,
    "email": "joao.pereira7904@hotmail.com",
    "endereco": "Rua da Paz, 840, Belo Horizonte",
    "escolaridade": "Fundamental Completo",
    "profissao": "Desenvolvedor",
    "nascimento": "05/03/1976",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 614,
    "nome": "Luísa Oliveira",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 1053197941,
    "email": "luisa.oliveira5467@outlook.com",
    "endereco": "Rua do Sol, 579, São Paulo",
    "escolaridade": "Superior Completo",
    "profissao": "Professor",
    "nascimento": "01/05/1975",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 660,
    "nome": "Pedro Martins",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 64314984081,
    "email": "pedro.martins4933@yahoo.com",
    "endereco": "Rua do Sol, 741, Porto Alegre",
    "escolaridade": "Superior Completo",
    "profissao": "Jornalista",
    "nascimento": "28/03/1959",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 668,
    "nome": "Rafael Silva",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 58047755742,
    "email": "rafael.silva8955@hotmail.com",
    "endereco": "Avenida Brasil, 967, Curitiba",
    "escolaridade": "Superior Completo",
    "profissao": "Professor",
    "nascimento": "03/07/2004",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 675,
    "nome": "João Silva",
    "nomeSocial": "",
    "genero": "Masculino",
    "cpf": 32741831764,
    "email": "joao.silva61@gmail.com",
    "endereco": "Rua da Paz, 990, Belo Horizonte",
    "escolaridade": "Médio Incompleto",
    "profissao": "Desenvolvedor",
    "nascimento": "24/10/1960",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 677,
    "nome": "Rafael Souza",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 83646237567,
    "email": "rafael.souza5658@hotmail.com",
    "endereco": "Travessa Central, 578, Porto Alegre",
    "escolaridade": "Fundamental Incompleto",
    "profissao": "Desenvolvedor",
    "nascimento": "04/04/1979",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 680,
    "nome": "Maria Santos",
    "nomeSocial": "",
    "genero": "Outro",
    "cpf": 70194756258,
    "email": "maria.santos2789@hotmail.com",
    "endereco": "Travessa Central, 752, Salvador",
    "escolaridade": "Fundamental Completo",
    "profissao": "Piloto",
    "nascimento": "03/06/1953",
    "tipoJurado": "Titular",
    "status": null
  },
  {
    "id": 729,
    "nome": "Fernanda Lima",
    "nomeSocial": "",
    "genero": "Feminino",
    "cpf": 687709896,
    "email": "fernanda.lima9895@hotmail.com",
    "endereco": "Travessa Central, 946, Rio de Janeiro",
    "escolaridade": "Superior Incompleto",
    "profissao": "Advogado",
    "nascimento": "09/06/1978",
    "tipoJurado": "Titular",
    "status": null
  }
]

export const juradosTitularesMock = juradosTitularesMockRawData.
  map(
    data => {
      const juradoBase = new Jurado(
        data.id,
        data.nome,
        data.nomeSocial,
        '',
        data.cpf,
        data.email,
        data.endereco,
        data.profissao,
        data.nascimento,
        data.genero,
        data.escolaridade
      );
      return new JuradoSorteado(juradoBase, data.tipoJurado);
    });